-- MySQL Script generated by MySQL Workbench
-- Sun Jul  5 15:39:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QandA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QandA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QandA` DEFAULT CHARACTER SET utf8 ;
USE `QandA` ;

-- -----------------------------------------------------
-- Table `QandA`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QandA`.`user` ;

CREATE TABLE IF NOT EXISTS `QandA`.`user` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_name` VARCHAR(45) NULL,
  `u_fname` VARCHAR(45) NULL,
  `u_lname` VARCHAR(45) NULL,
  `u_email` VARCHAR(75) NULL,
  `u_pwd` VARCHAR(300) NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QandA`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QandA`.`question` ;

CREATE TABLE IF NOT EXISTS `QandA`.`question` (
  `q_id` INT NOT NULL AUTO_INCREMENT,
  `q_title` VARCHAR(300) NULL,
  `q_tags` VARCHAR(300) NULL,
  `q_desc` VARCHAR(600) NULL,
  `user_u_id` INT NOT NULL,
  PRIMARY KEY (`q_id`),
  INDEX `fk_Question_User_idx` (`user_u_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_User`
    FOREIGN KEY (`user_u_id`)
    REFERENCES `QandA`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QandA`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QandA`.`answer` ;

CREATE TABLE IF NOT EXISTS `QandA`.`answer` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_desc` VARCHAR(1000) NOT NULL,
  `user_u_id` INT NOT NULL,
  `question_q_id` INT NOT NULL,
  PRIMARY KEY (`a_id`, `a_desc`),
  INDEX `fk_Answer_User1_idx` (`user_u_id` ASC) VISIBLE,
  INDEX `fk_Answer_Question1_idx` (`question_q_id` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_User1`
    FOREIGN KEY (`user_u_id`)
    REFERENCES `QandA`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`question_q_id`)
    REFERENCES `QandA`.`question` (`q_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
